#pragma once
#include <fstream>
#include <iomanip>
#include <cmath>
#include <iostream>
#include <stdexcept>
#include "imageHeader.h"
#include "BmpStructure.cpp"
#include "BMPReadAndPrintDetails.cpp"
#include "BmpReadAndWrite.cpp"
#include "BMPToGrayScale.cpp"
#include "brightening.cpp"
#include "CannyEdgeDetection.cpp"
#include "Convulation.cpp"
#include "ConvulationType2.cpp"
#include "histogramEqualiser.cpp"
#include "ImgNegative.cpp"
#include "ImgreadAndWrite.cpp"
#include "OtsusMethod.cpp"
#include "PrewittEdgeDetection.cpp"
#include "smoothing.cpp"
#include "SobelEdgeDetection.cpp"
#include "Threshold.cpp"

void BMPPrintDetailsUtility();
void BMPTOGrayScaleUtility();
void BrighteningUtility();
void CannyUtility();